### PR TITLE
Added support for CONN_MAX_AGE for Django 1.6+

### PR DESCRIPTION
**Pull request by peterfarrell**
Includes doco and tests.

### CODE REVIEW

**Comment by peterfarrell** [comment]
This passed tests on Travis:

https://travis-ci.org/kennethreitz/dj-database-url/builds/62033678

**Comment by gciding** [comment]
+1

**Comment by kennethreitz** [comment]
Love this! :sparkles: :cake: :sparkles:

**Comment by peterfarrell** [comment]
Yay!

**Pull request merged**
