### PR TITLE
Proper support for OPTIONS based on DATABASE_URL querystring

### PR DESCRIPTION
**Pull request by loisaidasam**
Based on initial work in [this pull request](https://github.com/kennethreitz/dj-database-url/pull/50), cleaned up, with querystring param parsing split into its own function.

### CODE REVIEW

**Comment by murphyke** [comment]
This PR is important.  I also am having to add SSL security to an existing project using dj-database-url.

**Comment by azreda** [comment]
+1 for supporting OPTIONS, which is needed for SSL and other settings.

**Comment by edmorley** [comment]
@kennethreitz I don't suppose you've had a chance to look at this? :-)

**Comment by joshowen** [comment]
+1

**Comment by kevinwmerritt** [comment]
+1

**Comment by nwp90** [comment]
+1. Without this, dj-database-url is unfortunately completely worthless to me.

**Comment by edmorley** [comment]
For anyone wanting this feature, I'd recommend [django-environ](https://github.com/joke2k/django-environ), it offers a superset of the dj-database-url functionality and also already supports this.

**Comment by anentropic** [comment]
+1

@loisaidasam maybe you could squash the commits to make a nice, tidy, appealing PR

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Pull request merged**
