### PR TITLE
Rename to newer setup.cfg wheel definition

### PR DESCRIPTION
**Pull request by graingert**
@kennethreitz can you also do a "python3 setup.py sdist bdist_wheel upload" please?

### CODE REVIEW

**Comment by kennethreitz** [comment]
this isn't necessary, and i prefer this pattern: 

https://github.com/kennethreitz/requests/blob/master/Makefile#L53

**Comment by graingert** [comment]
@kennethreitz I prefer this pattern, it's recommended by the PyPA, and it's one standard place to look for it.

**Comment by kennethreitz** [comment]
I don't care, the flag is all that is needed and we don't need the extra file.

**Comment by graingert** [comment]
sure, but the extra file should be removed, or correct.

**Comment by kennethreitz** [comment]
correct, it should be removed :)

**Pull request closed without merging**
